version: '2'
services:
  nginx:
    image: nginx:1.13.1
    ports:
      - "8081:80"
    volumes:
      - ./code:/code
      - ./containers/nginx/conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./logs:/var/log/nginx

  php:
    image: php:7-fpm
    volumes:
      - ./code:/code
      - ./containers/php/conf/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf

  db:
    image: mysql:8
    ports:
      - "8001:5432"
    volumes:
      - ./.database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
