nginx:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ./code:/code
    - ./contaners/nginx/conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
    - ./logs:/var/log/nginx
  links:
    - php
php:
  image: php:7-fpm
  volumes:
    - ./code:/code
    - ./contaners/php/conf/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
db:
  image: mysql:8
  volumes:
    - ./.database:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: example